### ISSUE TITLE
getSlotData() conflicting with pipes from MediaWiki Links

### ISSUE THREAD

**Issue by JimmyvanDelft** [Open-CSP/WSSlots#32]
## Steps to replicate the issue (include links if applicable):

1. Create a page with (for example) this content:

   ```wiki
   {{MyTemplate
   Text=Banana's are quite healthy. [[About apples|Apples]] are as well.
   }}```

2.	Then request slotdata from that page. I am doing it with LUA using p.getSlotData(page,slot).
3.	View the retrieved slotdata and see that the data for the parameter Text is cut-off at the pipe from the ‘apples’ link.

**What happens?:**

Parameter value cut off. See af_print in the screenshot:

![Image](https://github.com/user-attachments/assets/60d07a58-1409-4437-b50f-3363207c2a8e)

**What should have happened instead?:**

Complete parameter value.

## Also, there is no tag made yet for 4.6.0

**Comment by Designburo** [comment]
I've added a possible solution : https://github.com/WikibaseSolutions/mediawiki-template-parser/tree/bug/pipes-in-links

**Comment by marijnvanwezel** [comment]
@Designburo I cannot review the change because of the formatting you applied. It makes it impossible to see which changes you actually made.

Please apply the change without changing the formatting.

**Comment by marijnvanwezel** [comment]
This has been fixed in v2.2.0 of `mediawiki-template-parser`.

**Comment by Designburo** [comment]
That has to do with the MediaWiki code styling rules that are applied.

**Comment by JimmyvanDelft** [comment]
> This has been fixed in v2.2.0 of `mediawiki-template-parser`.

It is not fixed. Breaks when link has multiple pipes. @marijnvanwezel 

Link can have multiple pipes when used to display image for example `[[File:Methane Numbers Update.png|center|middle|border|Figure 1: Effect of hydrogen addition to natural gas on PKI methane number]]`
